services:
  db:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ctlogs
      POSTGRES_DB: ctlogs
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db_data:
    driver: local